name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t developertahvildari/multi-client ./client
      - run: docker build -t developertahvildari/multi-nginx  ./nginx
      - run: docker build -t developertahvildari/multi-server ./server
      - run: docker build -t developertahvildari/multi-worker ./worker
      - run: docker push developertahvildari/multi-client
      - run: docker push developertahvildari/multi-nginx
      - run: docker push developertahvildari/multi-client
      - run: docker push developertahvildari/multi-server
      - run: docker push developertahvildari/multi-worker
